spring:
  config:
    activate:
      on-profile: des
  datasource:
    url: jdbc:mariadb://localhost:3306/concentrapay
    username: root
    password: 123456
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update